[mongodb]
### Listening address of the MongoDB instance.
connect_url = "mongodb://mongo0:27017"

[api]
### API listening port. 
port = 8000

### CORS.
allow_origins = "*"

### JsonWebToken (JWT) credentials.
password_hash = "f36605441dd3b99a0448bc76f51f0e619f47051989cfcbf2fef18670f21799ad" # "password"
password_salt = "saltines"
jwt_expiration = "72h"

### Public API routes.
public_routes = [
    # Activated APIs.
    "api/analytics/v2/*",
    "api/core/v2/*",
]

[inx]
### Listening address of the node's INX interface.
connect_url = "http://localhost:9029"

### Time to wait until a new connection attempt is made.
connection_retry_interval = "5s"

### Maximum number of tries to establish an INX connection.
connection_retry_count = 30

[metrics]
### Whether metrics will be served.
enabled = false
